### ISSUE TITLE
I absolutely can't get this working for RDR 2

### ISSUE THREAD

**Issue by Monochrome94** [Killface1980/DualSense4Rockstar#11]
I downloaded the ZIP for RDR2 on this page
https://github.com/Killface1980/DualSense4Rockstar/tree/master/__RELEASE/RDR2
Dropped the files in my RDR2 EXE directory
I already had scripthook installed
DSX is downloaded.
I start the game and nothing with adaptive triggers or haptics is happening.

Are there steps im missing? Or settings in DSX i need?

**Comment by Killface1980** [comment]
Have you followed the guide posted here https://github.com/Killface1980/DualSense4Rockstar/tree/master/__RELEASE#readme ?

Does your folder structure looks like in the example? 
Do you also have ScriptHookDotNet installed? The version yu've downloaded requires v2. 
Any info in the Scripthook console?

**Comment by Monochrome94** [comment]
So my issue was I'm retarded and missed that I needed to put it in the scripts folder and not the RDR2 directory.  Think I only have one other mod that i need that for. 

Everything is working now thanks man.

**Comment by Killface1980** [comment]
Glad you got it working :-)
There's currently only one option, you can edit the newly generated file 'DualSense4RDR2.ini'.
It only has the option CANUSETHRESHOLD False and True. What it does: makes the gun fire not fire on the slightest touch of the trigger, only when pressed ~20%. Experimental, as it wasn't working with all emulation options the last time I checked.
