### ISSUE TITLE
RDR crash after apply the ScriptHookRDR2DotNet v2 by TuffyTown

### ISSUE THREAD

**Issue by PSerban93** [Killface1980/DualSense4Rockstar#13]
Hi, can you help me with this problem?
For me it's not working, after i apply all the files, and enter the game, it's crashing on loading screen.
If i delete the ScriptHookRDR2DotNetv2 files the game is loading and is working with RDR 2 PlayStation Icons Replacement and NativeTrainer.
Am I missing something?
Thank You!

**Comment by Killface1980** [comment]
Have you followed the installation guide? Do your folders/file structure look like in the example?

**Comment by PSerban93** [comment]
Yes, I followed the guide and DSX_Base.dll, DualSense4RDR2.dll and Newtonsoft.Json.dll are placed in scripts folder created in the main folder and their rest of the are placed next to game .exe.
I have an older version of the game. Do you think this is the problem?

**Comment by PSerban93** [comment]
Hi, I've manage to make it work.
The problem was the Playstation Icon Mod. Every LML is installed, the game crash, when i delete the vfs.asi file the game runs without problem.
Is there any solution for this problem?
Thank You!

**Comment by PSerban93** [comment]
The game crash if ScriptHookRDR2DotNet and LML versions are different.
