### ISSUE TITLE
Instruction's unclear?

### ISSUE THREAD

**Issue by RASTASTA12** [Killface1980/DualSense4Rockstar#14]
so I have never had to do anything like this to get a controller working so bare with me. I have download script hook that's fine and working both if them I'm sure of it as well as asi loader, but there is no script file any where? so create one yea... but where? in the root folder? then do I put your ddl file in there or do I put script hook ddl in there because I'm sure script hook is definitely supposed to be in the root folder? also it dose not seem to matter where I put your files no change in triggers or led at any point? also i assume DSX is meant to be open right? because if its not reddead don't read the controller and on it just keeps my default settings so what the hell am supposed to do?

**Comment by Killface1980** [comment]
Does this help?
https://github.com/Killface1980/DualSense4Rockstar/tree/master/__RELEASE
