### ISSUE TITLE
Mod triggers don't work GTA V

### ISSUE THREAD

**Issue by antoniorsk** [Killface1980/DualSense4Rockstar#16]
Hello, good evening, can someone help me please? I acquired the dsx through steam just to enable the adaptive triggers with mod in gta v, until 1 month ago they worked, but now the triggers don't work anymore, and I already left everything updated script hook v, I downloaded and uninstalled everything from the game, until the dsx I uninstalled and installed again, but the error continues, can you fix or update? I bought the program just for this reason and I can't use it anymore :(

in the game the error says that I don't have the folder: 'C:\Temp\DualSenseX\DualSenseX_PortNumber.txt'

and really this folder does not exist, is there an error with the dsx steam itself?

![dsx error](https://user-images.githubusercontent.com/129353410/228718974-9646b9e3-0ba4-41c3-afb5-adbb05225699.jpg)

**Comment by Kike096** [comment]
I have the same problem! could you solve it? Please help!!
