### ISSUE TITLE
Does not work. Help me please!

### ISSUE THREAD

**Issue by boykan313** [Killface1980/DualSense4Rockstar#19]
I did everything as in the instructions, the folders correspond to your example and do not work, what could be the problem? Help me please.

**Comment by boykan313** [comment]
![20230612120446_1](https://github.com/Killface1980/DualSense4Rockstar/assets/90963133/a4337da0-275c-4c27-9e90-410f4728dc6a)
![3222](https://github.com/Killface1980/DualSense4Rockstar/assets/90963133/3507b984-35b5-4b2f-854f-9ff658cc79f8)
![321](https://github.com/Killface1980/DualSense4Rockstar/assets/90963133/766d9cad-f046-4cbb-af67-ae090843b06d)

**Comment by Killface1980** [comment]
Not sure about it. I've had some hardware issues and currently have not enough disk space for RDR/GTA, so I cannot test for myself.
Are you using the free version of DSX or the current beta?
The error you have directs to a file access error, and/or something with ports.
I've created the mod from the at-that-time current template and have the line     
`string value = File.ReadAllText("C:\\Temp\\DualSenseX\\DualSenseX_PortNumber.txt");
`
Can you check if this file/path exists? You can create a blank file.

**Comment by ptb007** [comment]
I am also having the same issue. Please let me know if there is a fix!

**Comment by Killface1980** [comment]
Please go to the DSX app.

Check if there's a green light at 'Text File Status'.
If not, create an empty text file at `C:\Temp\DualSenseX\DualSenseX_PortNumber.txt`, and use the button in DSX to point to that file.
If it's green, make sure that the location is `C:\Temp\DualSenseX\DualSenseX_PortNumber.txt`.

**Comment by ptb007** [comment]
![image](https://github.com/Killface1980/DualSense4Rockstar/assets/136672011/9f628a7b-1390-4d86-a175-06126b529542)

**Comment by boykan313** [comment]
vashey pomoshchi.

I don't play games much now, but I'm interested in your project and
it's not clear why it doesn't work. would appreciate your help.


чт, 15 июн. 2023 г., 22:34 ptb007 ***@***.***>:

**Comment by boykan313** [comment]
> Пожалуйста, перейдите в приложение DSX.
> 
> Проверьте, горит ли зеленый свет в «Состоянии текстового файла». Если нет, создайте пустой текстовый файл по адресу `C:\Temp\DualSenseX\DualSenseX_PortNumber.txt`и используйте кнопку в DSX, чтобы указать на этот файл. Если он зеленый, убедитесь, что это местоположение `C:\Temp\DualSenseX\DualSenseX_PortNumber.txt`.

![3421](https://github.com/Killface1980/DualSense4Rockstar/assets/90963133/68d2ef0d-f1b0-4bcf-8724-aa5944c12cb8)
![20230618163124_1](https://github.com/Killface1980/DualSense4Rockstar/assets/90963133/cac67e12-4ba0-427a-a155-2ab1d7b78f30)
still doesn't help. strange, do you have any other ideas?

**Comment by cunyiles** [comment]
I have the same issue

**Comment by sijav** [comment]
create a text file if it doesn't exist: C:\Temp\DualSenseX\DualSenseX_PortNumber.txt
edit it and put 6969 in it and save it
![image](https://github.com/Killface1980/DualSense4Rockstar/assets/2679112/3b6351e6-9c38-47a2-9773-2ebab636d8c0)
make sure on the DSX app in the Settings -> Controller -> Networking you have enabled the UDP Port Listener and also The UDP Port is set to 6969
![image](https://github.com/Killface1980/DualSense4Rockstar/assets/2679112/39de4da9-1ce6-4cec-8bc1-2fa773ff1245)
That should be enough to run this mod

**Comment by Killface1980** [comment]
Should be fixed with the new release.

Please also update your Script Hook to 3.6, as the were a naming change in a method.
