### ISSUE TITLE
Crash after firing gun

### ISSUE THREAD

**Issue by Kr0sshair** [Killface1980/DualSense4Rockstar#20]
I had a little oopsie, uninstalled scriphook. Reinstalled it, yes v2, yes latest versions. Now every time i fire a gun my game freezes. And then i have to restart.

**Comment by Kr0sshair** [comment]
nevermind, for some reason no bullet trail mod did that

**Comment by Kr0sshair** [comment]
cus b4 it didnt do that

**Comment by Killface1980** [comment]
There was a naming change in ScriptHook 3.6 for 'get weapon time between shots'.
I've updated the mod, should work again.
