### ISSUE TITLE
Please, give me advice what to do in this case

### ISSUE THREAD

**Issue by SneKKaY** [Killface1980/DualSense4Rockstar#28]
![photo_2023-12-10_22-32-59](https://github.com/Killface1980/DualSense4Rockstar/assets/120265382/c4d7e117-6a7f-44d7-9423-75d0c0c3c0b8)

**Comment by tikh-iv** [comment]
Hello
Have you found any solution?

**Comment by SneKKaY** [comment]
> Hello
> Have you found any solution? 

No, I gave up

**Comment by tikh-iv** [comment]
> > Hello
> > Have you found any solution?
> 
> No, I gave up

I just found out
1) Use DualSenseX v2 (not v3 srteam version)
2) create `C:\temp\DualSenseX\DualSenseX_PortNumber.txt` with 
``` text
6969

```
3) Set up this file in Main page
4) Set up xbox emulation

After that it starts work

**Comment by Killface1980** [comment]
Duplicate of #15
