### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by JackHererx** [Killface1980/DualSense4Rockstar#8]
Hello, first of all I must say that I am using Google translate to write this message. Im sorry :/

It's my first time installing mods. 
I can't get my adaptive triggers to work. I've followed all the steps to install the mod and I can't see what I'm doing wrong. I leave some captures of my F8.

![Log1](https://user-images.githubusercontent.com/116851757/198420689-35cc68ce-2dfe-4cf6-9e24-278c7dfc244d.png)
![Log2](https://user-images.githubusercontent.com/116851757/198420720-0d6528bd-88a2-4cd9-a4d4-f655636c6cc7.png)
![log3](https://user-images.githubusercontent.com/116851757/198420716-536f5bd9-cbfa-494d-9858-481e67fb0746.png)

And here is my RDR2 folder and logs

![Folderandlogs](https://user-images.githubusercontent.com/116851757/198421812-c0ede09a-a955-4182-b49a-420c09cf01b7.png)

Thanks in advance!

**Comment by Killface1980** [comment]
I've added a new settings file in the last update which needs to be saved in your scripts folder. To save this file, RDR2 requires administrator access.

I've uploaded a new version which should load fine even after failing. You can find it in the release folder.

If this does not work, you can try setting RDR2.exe into admin mode. To do so, right click on RDR2.exe and select 'properties'. Select 'run as administrator' under the 'compatibility' tab.
![image](https://user-images.githubusercontent.com/16738568/198701020-c0c71ab3-3daa-4584-8ce9-5722dd987f01.png)

Let me know if this helps and I'm sorry for any innconveniences.

**Comment by JackHererx** [comment]
Hi! Sorry for the delay.

Its working now and its amazing. Thats a nice mod! 
I appreciate a lot your help. Thank you so much.
