### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by JohnGaming212** [Killface1980/DualSense4Rockstar#9]
I have absolutely no idea how I am meant to download this mod or which files to put where. Help would be appreciated as I cannot find any online.

PS: I am tying to play RDR2 and have it on the rockstar launcher

**Comment by Killface1980** [comment]
Head over to https://github.com/Killface1980/DualSense4Rockstar/tree/master/__RELEASE 
In the folders on top, you'll find the mod files for the adaptive triggers.
Below is a Readme with links to the required files like ScriptHook and a link to a short video showing how to install the ScriptHook mod.
Let me know if something's missing and I'll try to fill the blanks.
